### ISSUE TITLE
Migrate Seers Manuscript Item to Mekanism architecture

### ISSUE THREAD

**Issue by ax-vasquez** [ax-vasquez/enchantments-seer#19]
# Description
Now that the Mekanism architecture is in place, it's time to use it (yay)!

## To do
1. [x] Migrate logic from `com.nuggylib.enchantmentsseer.item.SeersManuscriptItem`
    1. [x] Move/update the logic so that it now lives within `com.nuggylib.enchantmentsseer.common.item.ItemSeersManuscript`
2. [x] Delete `SEERS_MANUSCRIPT` from `com.nuggylib.enchantmentsseer.EnchantmentsSeer`
    1. [x] Add a definition for `SEERS_MANUSCRIPT` in `com.nuggylib.enchantmentsseer.common.registries.EnchantmentsSeerItems` (use `SEERS_STONE` in the same file for reference - you can also check the referenced Mekanism file, but their version is much more complex)
3. [x] Update `com.nuggylib.enchantmentsseer.common.CreativeTabEnchantmentsSeer#makeIcon()` so that it uses the icon for the Seer's Manuscript instead of the Seer's Stone (as it currently does)

**Comment by armstrongl** [comment]
Done! See https://github.com/ax-vasquez/enchantments-seer/pull/20
