### ISSUE TITLE
Implement Seer's Manuscript

### ISSUE THREAD

**Issue by ax-vasquez** [ax-vasquez/enchantments-seer#5]
# Description
The Seer's Manuscript is the "highest tier" enchantment item in this mod. It will function as a reagent that allows the player to select any one enchantment to apply to the item in question. It grants full visibility for all applicable spells, as well as a slider to alter the level of the enchantment.

**With that said**, the Seer's Manuscript doesn't contain the enchantment logic. It's just a simple item that serves an important function when used in the Seer's Enchanting table

## To do
1. [x] Create a model and texture based on the vanilla book model/texture
    * [ ] Apply the "enchanted" effect
2. [x] Register Seer's Manuscript item
3. [x] Create a language definition for the new item (in `src/main/resources/assets/enchantments-seer/lang/en_us.json`)
4. [ ] Provide screenshot of the new item in-game and provide it in the PR

**Comment by armstrongl** [comment]
See PR #9
